### ISSUE TITLE
unable to install exec-as plugin

### ISSUE THREAD

**Issue by maxim-shilov-deel** [kubernetes-sigs/krew-index#3602] opened 2024-01-24 17:45 UTC
```
kubectl krew install exec-as
Updated the local copy of plugin index.
Installing plugin: exec-as
W0125 00:44:51.935642   68784 install.go:164] failed to install plugin "exec-as": install failed: failed to unpack into staging dir: failed to unpack the plugin archive: could not read archive: stream error: stream ID 1; NO_ERROR; received from peer
failed to install some plugins: [exec-as]: install failed: failed to unpack into staging dir: failed to unpack the plugin archive: could not read archive: stream error: stream ID 1; NO_ERROR; received from peer
```

**Comment by ahmetb** [comment] 2024-01-24 18:31
/kind support

This looks like a network error. Is it specifically only happening to this plugin and happening reproducibly?

If so, please close this issue and work with the plugin authors to address it.

**Closed** 2024-06-22 19:20 UTC
Labels: lifecycle/rotten, kind/support
